const columns = [
  { name: 'Collator', filterButton: true },
  { name: 'Transcriber', filterButton: true },
  { name: 'File Name', filterButton: true },
  { name: 'Category', filterButton: true },
  { name: 'Date Issued', filterButton: true },
  { name: 'Size (MB)', filterButton: true },
  { name: 'Duration (Mins)', filterButton: true },
  { name: 'Date Returned', filterButton: true },
  { name: 'Transcript Editor', filterButton: true },
  { name: 'Date Issued [TE]', filterButton: true },
  { name: 'Date Returned [TE]', filterButton: true },
];

const rows = [
  [
    'Ugochukwu',
    '',
    'glh-wed12121212'.toUpperCase(),
    'Sermon',
    '',
    40,
    60,
    '',
    '',
    '',
    '',
  ],
  [
    'Ugochukwu',
    'Ugochukwu',
    'glh-wed12121212'.toUpperCase(),
    'Sermon',
    new Date(new Date().toJSON()),
    40,
    60,
    new Date(new Date().toJSON()),
    'Ugochukwu',
    new Date(new Date().toJSON()),
    new Date(new Date().toJSON()),
  ],
  [
    'Ugochukwu',
    'Ugochukwu',
    'glh-wed12121212'.toUpperCase(),
    'Sermon',
    new Date(new Date().toJSON()),
    40,
    60,
    new Date(new Date().toJSON()),
    'Ugochukwu',
    new Date(new Date().toJSON()),
    new Date(new Date().toJSON()),
  ],
  [
    'Ugochukwu',
    'Ugochukwu',
    'glh-wed12121212'.toUpperCase(),
    'Sermon',
    new Date(new Date().toJSON()),
    40,
    60,
    new Date(new Date().toJSON()),
    'Ugochukwu',
    new Date(new Date().toJSON()),
    new Date(new Date().toJSON()),
  ],
];

module.exports = { rows, columns };
